staff_traning_homepage:
    path:     /hello/{name}
    defaults: { _controller: StaffTraningBundle:Default:index }

StaffTraningBundle_job:
        resource: "@StaffTraningBundle/Resources/config/routing/job.yml"
        prefix:   /job